### ISSUE TITLE
go get -u -v github.com/asticode/go-astilectron

### ISSUE THREAD

**Issue by SwankyTigerYY** [asticode/go-astikit#1]
D:\go_path\src\go-astilectron>go get -u -v github.com/asticode/go-astilectron
github.com/asticode/go-astilectron (download)
github.com/asticode/go-astikit (download)
github.com/asticode/go-astikit
# github.com/asticode/go-astikit
..\github.com\asticode\go-astikit\errors.go:65:11: undefined: errors.Unwrap
..\github.com\asticode\go-astikit\http.go:223:14: undefined: http.NewRequestWithContext
..\github.com\asticode\go-astikit\sync.go:479:9: undefined: errors.Is

**Comment by SwankyTigerYY** [comment]
I see. I need golang version greater than v1.13.0

**Comment by asticode** [comment]
That's it.

If you're looking to use `astilectron` with GO < 1.13 you can check the `v0.9.3` version.
