### ISSUE TITLE
Build failure for WASM

### ISSUE THREAD

**Issue by TACIXAT** [asticode/go-astikit#4]
Building with `GOARCH=wasm` and `GOOS=js` I hit the following failure. Trying to put astisub into a WASM module.

```
λ go get -u github.com/asticode/go-astisub/...
# github.com/asticode/go-astikit
..\..\go\src\github.com\asticode\go-astikit\os.go:129:14: undefined: syscall.SIGABRT
```

**Comment by asticode** [comment]
You're right, `SIGABRT` signal doesn't exist for `js,wasm` build targets.

I've pushed a fix. You can use `v0.8.0` tag.

Can you confirm this issue is fixed ?

**Comment by TACIXAT** [comment]
Works great, cheers!
